CODE RUB: Action variable for testing exception for retrieve all in student registration
hassanhabib/OtripleS pull request #1018
Opened 2022-01-27 01:15 UTC by deepshri7

2022-02-01 18:56 UTC, ShriHumrudha requested changes

2022-02-01 18:56 UTC, ShriHumrudha commented on OtripleS.Web.Api.Tests.Unit/Services/Foundations/StudentRegistrations/StudentRegistrationServiceTests.Exceptions.RetrieveAll.cs
> +
Please remove the extra lines 53 , 61

2022-02-05 17:33 UTC, hassanhabib commented on OtripleS.Web.Api.Tests.Unit/Services/Foundations/StudentRegistrations/StudentRegistrationServiceTests.Exceptions.RetrieveAll.cs
> +            Assert.Throws<StudentRegistrationDependencyException>(
This also should `StudentRegistrationServiceException`

2022-02-07 04:27 UTC, ShriHumrudha requested changes

2022-02-07 04:27 UTC, ShriHumrudha commented on OtripleS.Web.Api.Tests.Unit/Services/Foundations/StudentRegistrations/StudentRegistrationServiceTests.Exceptions.RetrieveAll.cs
> +
Extra line here can be removed.

2022-02-09 03:00 UTC, ShriHumrudha commented
@deepshri7, please fix the build failure.

2022-02-09 17:59 UTC, deepshri7 commented
Made new PR which run successfully...

2022-02-10 20:05 UTC, ShriHumrudha commented
@deepshri7 Got a conflict.

2022-02-11 04:06 UTC, closed without merging