CODE RUB: Action variable for testing exception for retrieve all in Calendar Entry Attachment
hassanhabib/OtripleS pull request #1031
Opened 2022-01-27 19:27 UTC by deepshri7

2022-01-30 00:57 UTC, hassanhabib commented on OtripleS.Web.Api.Tests.Unit/Services/Foundations/CalendarEntryAttachments/CalendarEntryAttachmentServiceTests.Exceptions.RetrieveAll.cs
> +
Remove this extra line @deepshri7

2022-01-30 00:58 UTC, hassanhabib commented on OtripleS.Web.Api.Tests.Unit/Services/Foundations/CalendarEntryAttachments/CalendarEntryAttachmentServiceTests.Exceptions.RetrieveAll.cs
> +
Make sure the build runs successfully

2022-02-14 23:46 UTC, ShriHumrudha requested changes

2022-02-14 23:46 UTC, ShriHumrudha commented on OtripleS.Web.Api.Tests.Unit/Services/Foundations/CalendarEntryAttachments/CalendarEntryAttachmentServiceTests.Exceptions.RetrieveAll.cs
> +            this.calendarEntryAttachmentService.RetrieveAllCalendarEntryAttachments();
Need tab here

2022-02-14 23:46 UTC, ShriHumrudha commented on OtripleS.Web.Api.Tests.Unit/Services/Foundations/CalendarEntryAttachments/CalendarEntryAttachmentServiceTests.Exceptions.RetrieveAll.cs
> +             retrieveAllCalenderEntryAttachmentAction);
Check the alignment here.

2022-02-15 19:40 UTC, ShriHumrudha approved these changes

2022-02-15 19:40 UTC, merged