CODE RUB: Action variable for testing exception for Retrieve all in Contact
hassanhabib/OtripleS pull request #1032
Opened 2022-01-27 19:43 UTC by deepshri7

2022-01-30 00:28 UTC, hassanhabib commented on OtripleS.Web.Api.Tests.Unit/Services/Foundations/Contacts/ContactServiceTests.Exceptions.RetrieveAll.cs
> +
Remove extra line here @deepshri7

2022-02-01 18:50 UTC, ShriHumrudha requested changes

2022-02-01 18:50 UTC, ShriHumrudha commented on OtripleS.Web.Api.Tests.Unit/Services/Foundations/Contacts/ContactServiceTests.Exceptions.RetrieveAll.cs
> +
In line 37 as well.

2022-02-14 23:52 UTC, ShriHumrudha requested changes

2022-02-14 23:52 UTC, ShriHumrudha commented on OtripleS.Web.Api.Tests.Unit/Services/Foundations/Contacts/ContactServiceTests.Exceptions.RetrieveAll.cs
> +            this.contactService.RetrieveAllContacts();
check your tab here and below as well.

2022-02-15 19:41 UTC, ShriHumrudha approved these changes

2022-02-15 20:12 UTC, merged