CODE RUB: Updated change variable add Assignment Attachment
hassanhabib/OtripleS pull request #1100
Opened 2022-01-31 23:45 UTC by deepshri7

2022-02-06 06:37 UTC, hassanhabib commented on OtripleS.Web.Api.Tests.Unit/Services/Foundations/AssignmentAttachments/AssignmentAttachmentServiceTests.Exceptions.Add.cs
> +            var Serviceexception = new Exception();
Remove the extra space at the end of this line.

2022-02-06 06:37 UTC, hassanhabib commented on OtripleS.Web.Api.Tests.Unit/Services/Foundations/AssignmentAttachments/AssignmentAttachmentServiceTests.Exceptions.Add.cs
> +            var Serviceexception = new Exception();
Also lower-case `ServiceException` to `serviceException`

2022-02-15 00:05 UTC, ShriHumrudha requested changes

2022-02-15 00:05 UTC, ShriHumrudha commented on OtripleS.Web.Api.Tests.Unit/Services/Foundations/AssignmentAttachments/AssignmentAttachmentServiceTests.Exceptions.Add.cs
> +
Remove extra line

2022-02-15 00:05 UTC, ShriHumrudha commented on OtripleS.Web.Api.Tests.Unit/Services/Foundations/AssignmentAttachments/AssignmentAttachmentServiceTests.Exceptions.Add.cs
> +
run code cleanup

2022-02-15 00:05 UTC, ShriHumrudha commented on OtripleS.Web.Api.Tests.Unit/Services/Foundations/StudentExamFees/StudentExamFeeServiceTests.Exceptions.RetrieveAll.cs
> +             this.studentExamFeeService.RetrieveAllStudentExamFees();
fix the tab here

2022-02-15 00:05 UTC, ShriHumrudha commented on OtripleS.Web.Api.Tests.Unit/Services/Foundations/StudentExamFees/StudentExamFeeServiceTests.Exceptions.RetrieveAll.cs
> +                  .Throws(exception);
Please run the build and test locally before committing the code.

2022-02-15 20:00 UTC, closed without merging