CODE RUB: Updated variable in retrieve all Calendar Entry
hassanhabib/OtripleS pull request #1155
Opened 2022-02-01 19:40 UTC by deepshri7

2022-02-06 08:32 UTC, hassanhabib commented
@deepshri7 fix the conflicts here.
Also separate each task in it's own PR.

2022-02-15 20:16 UTC, ShriHumrudha requested changes

2022-02-15 20:16 UTC, ShriHumrudha commented on OtripleS.Web.Api.Tests.Unit/Services/Foundations/CalendarEntries/CalendarEntryServiceTests.Exceptions.RetrieveAll.cs
> +
run code cleanup

2022-02-15 20:16 UTC, ShriHumrudha commented on OtripleS.Web.Api.Tests.Unit/Services/Foundations/CalendarEntries/CalendarEntryServiceTests.Exceptions.RetrieveAll.cs
> +           Action retrieveAllCalendarEntryAction = () =>
fix this

2022-02-15 20:41 UTC, ShriHumrudha commented on OtripleS.Web.Api.Tests.Unit/Services/Foundations/CalendarEntries/CalendarEntryServiceTests.Exceptions.RetrieveAll.cs
> +
@deepshri7 this is pending

2022-02-15 22:26 UTC, deepshri7 commented on OtripleS.Web.Api.Tests.Unit/Services/Foundations/CalendarEntries/CalendarEntryServiceTests.Exceptions.RetrieveAll.cs
> +           Action retrieveAllCalendarEntryAction = () =>
what change in this ?

2022-02-16 03:21 UTC, deepshri7 commented on OtripleS.Web.Api.Tests.Unit/Services/Foundations/CalendarEntries/CalendarEntryServiceTests.Exceptions.RetrieveAll.cs
> +           Action retrieveAllCalendarEntryAction = () =>
no changes

2022-02-16 03:30 UTC, ShriHumrudha commented
Difference is only extra tabs

2022-02-16 03:30 UTC, closed without merging