CODE RUB: Updated Variable in retrieve all Calendar Entry Attachments
hassanhabib/OtripleS pull request #1159
Opened 2022-02-01 21:15 UTC by deepshri7

2022-02-06 08:14 UTC, hassanhabib commented
@deepshri7 fix conflicts here please

2022-02-06 20:06 UTC, deepshri7 commented
No conflicts in this.

On Sun, 6 Feb 2022 at 00:14, Hassan Rezk Habib ***@***.***>
wrote:

> @deepshri7 <https://github.com/deepshri7> fix conflicts here please
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/hassanhabib/OtripleS/pull/1159#issuecomment-1030774569>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOHHWL2NWXUZMPVH23OUBRTUZYUVTANCNFSM5NKJEQPA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-02-16 21:52 UTC, ShriHumrudha requested changes

2022-02-16 21:52 UTC, ShriHumrudha commented on OtripleS.Web.Api.Tests.Unit/Services/Foundations/CalendarEntryAttachments/CalendarEntryAttachmentServiceTests.Exceptions.RetrieveAll.cs
> +            this.calendarEntryAttachmentService.RetrieveAllCalendarEntryAttachments();
Tab is required

2022-02-16 21:52 UTC, ShriHumrudha commented on OtripleS.Web.Api.Tests.Unit/Services/Foundations/CalendarEntryAttachments/CalendarEntryAttachmentServiceTests.Exceptions.RetrieveAll.cs
> +              retrieveAllCalendarEntryAttachmensAction);
check the alignment here

2022-02-16 21:52 UTC, ShriHumrudha commented on OtripleS.Web.Api.Tests.Unit/Services/Foundations/CalendarEntryAttachments/CalendarEntryAttachmentServiceTests.Exceptions.RetrieveAll.cs
> +             // when
remove this extra space

2022-02-22 19:44 UTC, closed without merging