CODE RUB: Updated variable in retrieve by Id Calendars
hassanhabib/OtripleS pull request #1165
Opened 2022-02-01 23:28 UTC by deepshri7

2022-02-06 08:00 UTC, hassanhabib commented
@deepshri7 address conflicts here please

2022-02-15 06:06 UTC, ShriHumrudha requested changes

2022-02-15 06:06 UTC, ShriHumrudha commented on OtripleS.Web.Api.Tests.Unit/Services/Foundations/Calendars/CalendarServiceTests.Exceptions.RetriveById.cs
> +                 .ThrowsAsync(serviceException);
Fix the tab here.

2022-02-15 20:26 UTC, ShriHumrudha approved these changes

2022-02-15 20:29 UTC, merged