CODE RUB: changed action variable in retrieve all exam attachments
hassanhabib/OtripleS pull request #1281
Opened 2022-02-03 19:16 UTC by deepshri7

2022-02-06 08:26 UTC, hassanhabib commented
@deepshri7 fix the conflicts here.

2022-02-16 21:53 UTC, ShriHumrudha requested changes

2022-02-16 21:53 UTC, ShriHumrudha commented on OtripleS.Web.Api.Tests.Unit/Services/Foundations/ExamAttachments/ExamAttachmentServiceTests.Exceptions.RetrieveAll.cs
> +            // when
remove this space

2022-02-24 06:02 UTC, ShriHumrudha commented
Closing the PR as it is beyond the 3-day window.

2022-02-24 06:02 UTC, closed without merging