MinorFix: Course Validation Invalid Status
hassanhabib/OtripleS pull request #1372
Opened 2022-02-06 01:16 UTC by tsatay

2022-02-06 08:17 UTC, hassanhabib commented
@tsatay we need to make tests are passing here.

2022-02-10 00:31 UTC, hassanhabib commented on OtripleS.Web.Api.Tests.Unit/Services/Foundations/Courses/CourseServiceTests.cs
> +            return (T)(object)randomNumber;
Just add one line above this one.

2022-02-10 00:32 UTC, hassanhabib commented on OtripleS.Web.Api.Tests.Unit/Services/Foundations/Courses/CourseServiceTests.cs
> +            while(Enum.IsDefined(typeof(T), randomNumber) is true)
Add just one line above this one.

2022-02-16 21:54 UTC, ShriHumrudha commented
@tsatay , need your attention here.

2022-02-17 00:33 UTC, tsatay commented on OtripleS.Web.Api.Tests.Unit/Services/Foundations/Courses/CourseServiceTests.cs
> +            return (T)(object)randomNumber;
It's fixed.

2022-02-17 00:33 UTC, tsatay commented on OtripleS.Web.Api.Tests.Unit/Services/Foundations/Courses/CourseServiceTests.cs
> +            while(Enum.IsDefined(typeof(T), randomNumber) is true)
it's fixed

2022-02-17 00:42 UTC, ShriHumrudha requested changes

2022-02-17 00:42 UTC, ShriHumrudha commented on OtripleS.Web.Api.Tests.Unit/Services/Foundations/Courses/CourseServiceTests.Validations.Add.cs
> +
This line needs to be removed.

2022-02-17 01:14 UTC, tsatay commented on OtripleS.Web.Api.Tests.Unit/Services/Foundations/Courses/CourseServiceTests.Validations.Add.cs
> +
It's fixed

2022-02-17 03:25 UTC, ShriHumrudha approved these changes

2022-02-17 03:25 UTC, merged