CODE RUB: Action variable updated fix in testing exceptions for retrieve all calendar entries
hassanhabib/OtripleS pull request #1552
Opened 2022-02-07 18:58 UTC by deepshri7

2022-02-11 03:24 UTC, hassanhabib commented
@deepshri7 please fix the conflicts

2022-02-11 03:40 UTC, hassanhabib commented
@deepshri7 please fix conflict issue

2022-02-15 06:07 UTC, ShriHumrudha requested changes

2022-02-15 06:07 UTC, ShriHumrudha commented on OtripleS.Web.Api.Tests.Unit/Services/Foundations/CalendarEntries/CalendarEntryServiceTests.Exceptions.RetrieveAll.cs
> +
Run code cleanup

2022-02-15 06:07 UTC, ShriHumrudha commented on OtripleS.Web.Api.Tests.Unit/Services/Foundations/CalendarEntries/CalendarEntryServiceTests.Exceptions.RetrieveAll.cs
> +            this.calendarEntryService.RetrieveAllCalendarEntries();
Fix the tab here and below.

2022-02-15 21:23 UTC, ShriHumrudha requested changes

2022-02-15 21:23 UTC, ShriHumrudha commented on OtripleS.Web.Api.Tests.Unit/Services/Foundations/CalendarEntries/CalendarEntryServiceTests.Exceptions.RetrieveAll.cs
> +            this.calendarEntryService.RetrieveAllCalendarEntries();
@deepshri7 this needs attention

2022-02-15 21:47 UTC, ShriHumrudha approved these changes

2022-02-15 21:51 UTC, merged