Users/devanteconnor/coderub fix one liner exam
hassanhabib/OtripleS pull request #1646
Opened 2022-02-13 20:49 UTC by devanteconnor

2022-02-14 23:43 UTC, ShriHumrudha requested changes

2022-02-14 23:43 UTC, ShriHumrudha commented on OtripleS.Web.Api.Tests.Unit/Services/Foundations/AssignmentAttachments/AssignmentAttachmentServiceTests.cs
This change is not required

2022-02-14 23:43 UTC, ShriHumrudha commented on OtripleS.Web.Api.Tests.Unit/Services/Foundations/AssignmentAttachments/AssignmentAttachmentServiceTests.cs
> +            var filler =
this is not required

2022-02-14 23:43 UTC, ShriHumrudha commented
Fix your PR title too.

2022-02-18 00:36 UTC, hassanhabib commented
@devanteconnor there are two things required here:
1. Revert the changes that @ShriHumrudha indicated are not needed on the same branch.
2. Make sure you properly name the PR.

2022-02-24 06:04 UTC, ShriHumrudha commented
Closing the PR as it is beyond the 3-day window.

2022-02-24 06:04 UTC, closed without merging