CODE RUB: Replace Input variables in Exception Tests with Some variable
hassanhabib/OtripleS pull request #1678
Opened 2022-02-15 03:40 UTC by KFitz114

2022-02-15 05:18 UTC, ShriHumrudha requested changes

2022-02-15 05:18 UTC, ShriHumrudha commented on OtripleS.Web.Api.Tests.Unit/Services/Foundations/GuardianAttachments/GuardianAttachmentServiceTests.Exceptions.RetrieveById.cs
> +                (someGuardianId, someAttachmentId);
Fix the alignment here and in the below tests as well.

2022-02-16 03:30 UTC, ShriHumrudha approved these changes

2022-02-16 03:31 UTC, ShriHumrudha requested changes
Got conflicts.

2022-02-16 20:08 UTC, KFitz114 commented
> Got conflicts.

@ShriHumrudha Resolved conflicts and committed merge.

2022-02-16 20:11 UTC, ShriHumrudha approved these changes

2022-02-16 20:35 UTC, merged