MINOR FIX :  Student Guardian Service Exception Add
hassanhabib/OtripleS pull request #1697
Opened 2022-02-16 06:10 UTC by tharanisantosh

2022-02-16 18:19 UTC, ShriHumrudha requested changes

2022-02-16 18:19 UTC, ShriHumrudha commented on OtripleS.Web.Api.Tests.Unit/Services/Foundations/StudentGuardians/StudentGuardianServiceTests.Exceptions.Remove.cs
>              var expectedStudentGuardianException =
expectedStudentGuardian**Service**Exception

2022-02-16 18:19 UTC, ShriHumrudha commented on OtripleS.Web.Api/Models/StudentGuardians/Exceptions/FailedStudentGuardianServiceException.cs
> +            : base(message: "Failed student guardian sevice error occured.",innerException)
contact support.",<space> innerException

2022-02-17 03:11 UTC, tharanisantosh commented on OtripleS.Web.Api.Tests.Unit/Services/Foundations/StudentGuardians/StudentGuardianServiceTests.Exceptions.Remove.cs
>              var expectedStudentGuardianException =
Comment Resolved.

2022-02-17 03:12 UTC, ShriHumrudha approved these changes

2022-02-17 03:18 UTC, merged