MINOR FIX : Calendar Entry Attachment Service Exception
hassanhabib/OtripleS pull request #1699
Opened 2022-02-16 07:45 UTC by imjane5

2022-02-16 18:15 UTC, ShriHumrudha requested changes

2022-02-16 18:15 UTC, ShriHumrudha commented on OtripleS.Web.Api.Tests.Unit/Services/Foundations/CalendarEntryAttachments/CalendarEntryAttachmentServiceTests.Exceptions.Add.cs
> +                new FailedCalendarEntryAttachment(serviceException);
FailedCalendarEntry**Service**Attachment

2022-02-16 23:03 UTC, ShriHumrudha requested changes

2022-02-16 23:03 UTC, ShriHumrudha commented on OtripleS.Web.Api.Tests.Unit/Services/Foundations/CalendarEntryAttachments/CalendarEntryAttachmentServiceTests.Exceptions.Add.cs
> +                new FailedCalendarEntryServiceAttachment(serviceException);
Sorry for the typo previously, it is Failed<Entity>ServiceException so it is FailedCalendarEntryAttachmentServiceException

2022-02-16 23:03 UTC, imjane5 commented on OtripleS.Web.Api.Tests.Unit/Services/Foundations/CalendarEntryAttachments/CalendarEntryAttachmentServiceTests.Exceptions.Add.cs
> +                new FailedCalendarEntryAttachment(serviceException);
Updated. Please check

2022-02-17 03:11 UTC, ShriHumrudha requested changes

2022-02-17 03:11 UTC, ShriHumrudha commented on OtripleS.Web.Api.Tests.Unit/Services/Foundations/CalendarEntryAttachments/CalendarEntryAttachmentServiceTests.Exceptions.Add.cs
> +            var failedCalendarEntryAttachmentService =
failedCalendarEntryAttachmentServiceException should be the variable name. Please verify in all the places.

2022-02-18 06:45 UTC, ShriHumrudha approved these changes

2022-02-18 06:45 UTC, merged