MINOR FIX :  Student Exam Service Exception Add
hassanhabib/OtripleS pull request #1700
Opened 2022-02-16 08:14 UTC by tharanisantosh

2022-02-16 18:16 UTC, ShriHumrudha requested changes

2022-02-16 18:16 UTC, ShriHumrudha commented on OtripleS.Web.Api/Models/StudentExams/Exceptions/FailedStudentExamServiceException.cs
> +            : base(message: "Failed student exam service error occured.",innerException)
contact support.","<space>innerException

2022-02-16 18:16 UTC, ShriHumrudha commented on OtripleS.Web.Api.Tests.Unit/Services/Foundations/StudentExams/StudentExamServiceTests.Validations.Remove.cs
> +            var expectedStudentExamServiceException = new StudentExamServiceException(failedStudentExamServiceException);
can be broken to two lines

2022-02-17 02:48 UTC, ShriHumrudha requested changes

2022-02-17 02:48 UTC, ShriHumrudha commented on OtripleS.Web.Api.Tests.Unit/Services/Foundations/StudentExams/StudentExamServiceTests.Validations.Remove.cs
> +            var expectedStudentExamServiceException = new StudentExamServiceException(failedStudentExamServiceException);
@tharanisantosh this is pending

2022-02-17 03:01 UTC, tharanisantosh commented on OtripleS.Web.Api.Tests.Unit/Services/Foundations/StudentExams/StudentExamServiceTests.Validations.Remove.cs
> +            var expectedStudentExamServiceException = new StudentExamServiceException(failedStudentExamServiceException);
Comment Resolved.

2022-02-17 03:02 UTC, ShriHumrudha approved these changes

2022-02-17 03:10 UTC, merged