MINOR FIX : Student Exam Fee Service Exception Add
hassanhabib/OtripleS pull request #1701
Opened 2022-02-16 08:53 UTC by tharanisantosh

2022-02-16 18:10 UTC, ShriHumrudha requested changes

2022-02-16 18:10 UTC, ShriHumrudha commented on OtripleS.Web.Api/Models/StudentExamFees/Exceptions/FailedStudentExamFeeServiceException.cs
> +            : base(message: "Failed student exam fee service error occured." ,innerException)
contact support.",<space>innerException

2022-02-17 02:30 UTC, tharanisantosh commented on OtripleS.Web.Api/Models/StudentExamFees/Exceptions/FailedStudentExamFeeServiceException.cs
> +            : base(message: "Failed student exam fee service error occured." ,innerException)
Comment Resolved.

2022-02-17 02:46 UTC, ShriHumrudha requested changes

2022-02-17 02:46 UTC, ShriHumrudha commented on OtripleS.Web.Api.Tests.Unit/Services/Foundations/StudentExamFees/StudentExamFeeServiceTests.Exceptions.Remove.cs
> +            var expectedStudentExamFeeException =
expectedStudentExamFee**Service**Exception

2022-02-17 02:57 UTC, ShriHumrudha approved these changes

2022-02-17 02:57 UTC, merged