MINOR FIX : Student Attachment Service Exception Add
hassanhabib/OtripleS pull request #1704
Opened 2022-02-16 18:24 UTC by tharanisantosh

2022-02-16 19:02 UTC, ShriHumrudha requested changes

2022-02-16 19:02 UTC, ShriHumrudha commented on OtripleS.Web.Api/Models/StudentAttachments/Exceptions/FailedStudentAttachmentServiceException.cs
> +            : base(message: "Failed student attachment service error occured,contact support." ,innerException)
: base(message: "Failed student attachment service error occurred, contact support.", innerException)

2022-02-16 19:42 UTC, ShriHumrudha requested changes

2022-02-16 19:42 UTC, ShriHumrudha commented on OtripleS.Web.Api/Models/StudentAttachments/Exceptions/FailedStudentAttachmentServiceException.cs
> +            : base(message: "Failed student attachment service error occured,contact support.",innerException)
: base(message: "Failed student attachment service error occurred, contact support.", innerException)

2022-02-16 20:04 UTC, tharanisantosh commented on OtripleS.Web.Api/Models/StudentAttachments/Exceptions/FailedStudentAttachmentServiceException.cs
> +            : base(message: "Failed student attachment service error occured,contact support." ,innerException)
Comment Resolved. Thanks Humrudha.

2022-02-16 20:06 UTC, ShriHumrudha requested changes

2022-02-16 20:06 UTC, ShriHumrudha commented on OtripleS.Web.Api/Models/StudentAttachments/Exceptions/FailedStudentAttachmentServiceException.cs
> +            : base(message:"Failed student attachment service error occured,contact support.",innerException)
: base(message: "Failed student attachment service error occurred, contact support.", innerException)

2022-02-16 21:48 UTC, ShriHumrudha requested changes

2022-02-16 21:48 UTC, ShriHumrudha commented on OtripleS.Web.Api/Models/StudentAttachments/Exceptions/FailedStudentAttachmentServiceException.cs
> +            :base(message:"Failed student attachment service error occured,contact support.",innerException)
: base(message: "Failed student attachment service error occurred, contact support.", innerException)

Please take care of the alignment

2022-02-17 02:49 UTC, ShriHumrudha approved these changes

2022-02-17 02:49 UTC, merged