MINOR FIX : Guardian Service Exception Add
hassanhabib/OtripleS pull request #1728
Opened 2022-02-18 19:27 UTC by tharanisantosh

2022-02-19 05:12 UTC, ShriHumrudha requested changes

2022-02-19 05:12 UTC, ShriHumrudha commented on OtripleS.Web.Api/Models/Guardians/Exceptions/FailedGuardianServiceException.cs
> +            : base(message: "Failed Guardian service error occurred, contact support.", innerException)
small g

2022-02-20 04:45 UTC, tharanisantosh commented on OtripleS.Web.Api/Models/Guardians/Exceptions/FailedGuardianServiceException.cs
> +            : base(message: "Failed Guardian service error occurred, contact support.", innerException)
Comment Resolved.

2022-02-20 04:45 UTC, tharanisantosh commented on OtripleS.Web.Api/Models/Guardians/Exceptions/FailedGuardianServiceException.cs
> +
Comment Resolved.

2022-02-20 06:03 UTC, ShriHumrudha approved these changes

2022-02-20 06:03 UTC, merged