CODE RUB: Replace default with Guid.Empty
hassanhabib/OtripleS pull request #1741
Opened 2022-02-19 04:21 UTC by KFitz114

2022-02-19 05:22 UTC, ShriHumrudha requested changes

2022-02-21 13:59 UTC, KFitz114 commented on OtripleS.Web.Api.Tests.Unit/Services/Foundations/Teachers/TeacherServiceTests.Validations.RetrieveById.cs
> +            Guid inputTeacherId = invalidTeacherId;
@ShriHumrudha Removed input and replaced random with invalid.

2022-02-22 01:00 UTC, ShriHumrudha approved these changes

2022-02-22 01:01 UTC, ShriHumrudha requested changes
Resolve the conflict

2022-02-25 06:40 UTC, ShriHumrudha commented
Closing as it has been open for more than 3 days.

2022-02-25 06:40 UTC, closed without merging