MINOR FIX :  Guardian Contact Service Exception Add
hassanhabib/OtripleS pull request #1746
Opened 2022-02-19 06:04 UTC by tharanisantosh

2022-02-19 07:57 UTC, ShriHumrudha requested changes

2022-02-19 07:57 UTC, ShriHumrudha commented on OtripleS.Web.Api/Models/GuardianContacts/Exceptions/FailedGuardianContactServiceException.cs
> +            : base(message: "Failed semester course service error occurred, contact support.", innerException)
guardian contact

2022-02-20 04:29 UTC, tharanisantosh commented on OtripleS.Web.Api/Models/GuardianContacts/Exceptions/FailedGuardianContactServiceException.cs
> +            : base(message: "Failed semester course service error occurred, contact support.", innerException)
Comment resolved

2022-02-20 04:51 UTC, tharanisantosh commented on OtripleS.Web.Api/Models/GuardianContacts/Exceptions/FailedGuardianContactServiceException.cs
> +            : base(message: "Failed semester course service error occurred, contact support.", innerException)
Comment Resolved

2022-02-20 06:03 UTC, ShriHumrudha approved these changes

2022-02-20 06:03 UTC, merged