MINOR FIX : Course Attachments Service Exception
hassanhabib/OtripleS pull request #1751
Opened 2022-02-19 22:06 UTC by imjane5

2022-02-19 23:11 UTC, ShriHumrudha requested changes

2022-02-19 23:11 UTC, ShriHumrudha commented on OtripleS.Web.Api.Tests.Unit/Services/Foundations/CourseAttachments/CourseAttachmentServiceTests.Exceptions.Add.cs
> +
Remove this extra line

2022-02-19 23:11 UTC, ShriHumrudha commented on OtripleS.Web.Api.Tests.Unit/Services/Foundations/CourseAttachments/CourseAttachmentServiceTests.Exceptions.Remove.cs
> +            var expectedCourseAttachmentException =
epxectedCourseAttachmentServiceException

2022-02-20 02:18 UTC, ShriHumrudha requested changes

2022-02-20 02:18 UTC, ShriHumrudha commented on OtripleS.Web.Api/Models/CoursesAttachments/Exceptions/FailedCourseAttachmentServiceException.cs
> +             : base(message: "Failed classroom service error occured, contact support.",
Failed course attachment service....

2022-02-20 04:13 UTC, imjane5 commented on OtripleS.Web.Api/Models/CoursesAttachments/Exceptions/FailedCourseAttachmentServiceException.cs
> +             : base(message: "Failed classroom service error occured, contact support.",
Changed the error message

2022-02-20 06:02 UTC, ShriHumrudha approved these changes

2022-02-20 06:02 UTC, merged