CODERUB: Separate Logic Test For Create Operation - Teachers
hassanhabib/OtripleS pull request #2037
Opened 2022-03-10 08:09 UTC by tharanisantosh

2022-03-10 23:46 UTC, ShriHumrudha requested changes
Got conflicts. Address the title and link the issue too.

2022-03-13 18:45 UTC, ShriHumrudha commented
Beyond the 3 day window.

2022-03-17 05:14 UTC, ShriHumrudha commented
@tharanisantosh reopening as per your request

2022-03-17 06:56 UTC, ShriHumrudha requested changes

2022-03-17 06:56 UTC, ShriHumrudha commented on OtripleS.Web.Api.Tests.Unit/Services/Foundations/Teachers/TeacherServiceTests.Logic.Create.cs
> +using System;
Run code cleanup

2022-03-17 07:13 UTC, ShriHumrudha approved these changes
@tharanisantosh use appropriate PR title

2022-03-17 07:13 UTC, merged

2022-03-17 07:16 UTC, tharanisantosh commented
> @tharanisantosh use appropriate PR title

Ok Humrudha. Noted.

2022-03-17 07:19 UTC, tharanisantosh commented on OtripleS.Web.Api.Tests.Unit/Services/Foundations/Teachers/TeacherServiceTests.Logic.Create.cs
> +using System;
Code cleanup completed.