CODE RUB: AssignmentAttachments on Add Service Exception
hassanhabib/OtripleS pull request #2163
Opened 2022-03-22 20:52 UTC by imjane5

2022-03-22 21:38 UTC, ShriHumrudha requested changes

2022-03-22 21:38 UTC, ShriHumrudha commented on OtripleS.Api.Infrastructure.Provision/OtripleS.Web.Api.Infrastructure.Provision.csproj
> +    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.0-preview.2.22153.1" />
Do one change at a time. Is this intended for package update or exceptions code rub?

2022-03-26 20:28 UTC, hassanhabib commented
Closing due to inactivity

2022-03-26 21:58 UTC, ShriHumrudha commented
@hassanhabib The PR is blocked due to the failing acceptance test. I have been re-triggering still no luck. So re-opening to try again.

2022-03-26 22:58 UTC, ShriHumrudha approved these changes

2022-03-26 22:58 UTC, merged