CODE RUB: Order Crud Operation For Teachercontacts
hassanhabib/OtripleS pull request #2252
Opened 2022-04-05 06:15 UTC by nedataghiparast

2022-04-09 03:07 UTC, ShriHumrudha requested changes

2022-04-09 03:07 UTC, ShriHumrudha commented on OtripleS.Web.Api/Services/Foundations/UserContacts/UserContactService.cs
> +
Remove this line

2022-04-11 07:00 UTC, nedataghiparast commented
@ShriHumrudha Done Please take another look

2022-04-11 21:51 UTC, ShriHumrudha requested changes

2022-04-11 21:51 UTC, ShriHumrudha commented on OtripleS.Web.Api/Services/Foundations/UserContacts/UserContactService.cs
> +
I still see the line 64

2022-04-16 21:03 UTC, ShriHumrudha commented
Closing due to inactivity.

2022-04-16 21:03 UTC, closed without merging