ExamFee entity model
hassanhabib/OtripleS pull request #349
Opened 2021-04-13 11:43 UTC by bilalmehrban

- ExamFee Model Setup & Migrations with EF Core
- ExamFee Broker Select By Id function
- ExamFee Broker Select All function 
- ExamFee Broker Insert function 
- ExamFee Broker Delete function 
- ExamFee Broker Update function

2021-04-13 16:59 UTC, hassanhabib commented on OtripleS.Web.Api/Migrations/20210413113346_ExamFee.cs
> +﻿using System;
Add the copyrights notes here please

2021-04-13 16:59 UTC, hassanhabib commented on OtripleS.Web.Api/Migrations/20210413121338_UpdatedExamFeeModel.cs
> +﻿using Microsoft.EntityFrameworkCore.Migrations;
Add copyrights notice here as well

2021-04-13 17:00 UTC, hassanhabib commented on OtripleS.Web.Api/Models/ExamFees/ExamFee.cs
> +    }
Put this enum in it's own file under the same namespace/folder

2021-04-13 17:00 UTC, hassanhabib commented
@bilalmehrban just a couple of comments.
@viralpandya please take a look at this PR as well when you get a moment.

2021-04-14 01:10 UTC, viralpandya approved these changes

2021-04-14 02:45 UTC, viralpandya commented on OtripleS.Web.Api/Brokers/Storage/StorageBroker.ExamFees.References.cs
> +                .HasOne(examFee => examFee.CreatedByUser)
We need to create relation between (Exam, Fees) table with ExamFees

2021-04-14 02:48 UTC, viralpandya requested changes
Please add relationship between ExamFee <---> Fee and Exam <--> ExamFee.

2021-04-14 07:33 UTC, merged