CODE RUB: Localize Dependency Exceptions - Contacts
hassanhabib/OtripleS pull request #813
Opened 2021-11-18 21:44 UTC by arafat-pro

Closes #530

2021-11-19 17:43 UTC, ShriHumrudha requested changes

2021-11-19 17:43 UTC, ShriHumrudha commented on OtripleS.Web.Api/Models/Contacts/Exceptions/FailedContactStorageException.cs
> +﻿using System;
Add copyrights header.

2021-11-19 17:43 UTC, ShriHumrudha commented on OtripleS.Web.Api/Models/Contacts/Exceptions/FailedContactStorageException.cs
> +            :base("Failed contact storage error occurred, contact support.", innerException)
Parameter alias (message: ..)
Run code clean up.

2021-11-20 12:39 UTC, arafat-pro commented on OtripleS.Web.Api/Models/Contacts/Exceptions/FailedContactStorageException.cs
> +﻿using System;
thanks for the identification!

2021-11-20 12:40 UTC, arafat-pro commented on OtripleS.Web.Api/Models/Contacts/Exceptions/FailedContactStorageException.cs
> +            :base("Failed contact storage error occurred, contact support.", innerException)
Parameterized alias as advised!

2021-11-20 14:52 UTC, ShriHumrudha approved these changes

2021-11-21 16:32 UTC, merged