CODE RUB: Filler Method Order
hassanhabib/OtripleS pull request #818
Opened 2021-11-19 02:22 UTC by Shrabanac

2021-11-19 02:23 UTC, ShriHumrudha requested changes

2021-11-19 02:23 UTC, ShriHumrudha commented on OtripleS.Web.Api.Tests.Unit/Services/Foundations/TeacherContacts/TeacherContactServiceTests.cs
> +            filler.Setup()
Need a new line space

2021-11-19 03:12 UTC, ShriHumrudha commented
@Shrabanac You got some conflicts.

2021-11-23 17:45 UTC, hassanhabib commented
Closing this due to inactivity.

2021-11-23 17:45 UTC, closed without merging