CODERUB: Remove Storage Validations from Calendar Retrieve All
hassanhabib/OtripleS pull request #836
Opened 2021-11-19 23:46 UTC by SallyDeveloper

2021-11-20 01:41 UTC, ShriHumrudha requested changes

2021-11-20 01:41 UTC, ShriHumrudha commented on OtripleS.Web.Api/Services/Foundations/Attendances/AttendanceService.cs
> +        TryCatch(() => this.storageBroker.SelectAllAttendances());
Remove attendance from this PR.

2021-11-20 03:42 UTC, hassanhabib commented
@SallyDeveloper tests are still failing. You have to remove the failing test.

2021-11-23 03:07 UTC, hassanhabib commented
Shutting this down due to inactivity

2021-11-23 03:07 UTC, closed without merging